name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # steps:
    # - uses: actions/checkout@v3
    # - name: Setup .NET
    #   uses: actions/setup-dotnet@v2
    #   with:
    #     dotnet-version: 5.0.x
    # - name: Restore dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --no-restore
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
      
    
    - name: Unity - Test runner
      # You may pin to the exact commit or the version.
      # uses: game-ci/unity-test-runner@d95f760d49621753209829b206793e6d5c7b86bd
      uses: game-ci/unity-test-runner@v2.0.2
      with:
        # Version of unity to use for testing the project. Use "auto" to get from your ProjectSettings/ProjectVersion.txt
        unityVersion: auto # optional, default is auto
        # Specific docker image that should be used for testing the project
        # customImage: # optional, default is 
        # Path to the Unity project to be tested.
        projectPath: ./ # optional
        # Extra parameters to configure the Unity editor run.
        # customParameters: # optional
        # The type of tests to be run by the test runner.
        # testMode: # optional, default is all
        # Optional coverage parameters for the -coverageOptions argument.
        # coverageOptions: # optional, default is generateAdditionalMetrics;generateHtmlReport;generateBadgeReport
        # Path where test artifacts should be stored.
        # artifactsPath: # optional, default is artifacts
        # Initialises Docker using the host network.
        # useHostNetwork: # optional
        # SSH Agent path to forward to the container.
        # sshAgent: # optional, default is 
        # GitHub Private Access Token (PAT) to pull from GitHub.
        # gitPrivateToken: # optional, default is 
        # Token to authorize access to the GitHub REST API. If provided, a check run will be created with the test results.
        # githubToken: # optional, default is 
        # Name for the check run that is created when a github token is provided.
        # checkName: # optional, default is Test Results
